### ISSUE TITLE
add social media html tags

### ISSUE THREAD

**Issue by MdAbedin** [hacknyu/website-2020#4]
sites like fb and twitter scan the html of web pages for specific tags to determine how to display them when linked on their site. adding these will improve our look on these sites.

where to learn:
[facebook open graph](https://developers.facebook.com/docs/sharing/webmasters/)
[twitter cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards)

**Comment by kevin-chen** [comment]
finished, opened pull request
